/**
 * Created by adin on 10/23/15
 * email: phpgege@163.com
 */


var res = {
    listBg: 'listBg.png',
    indexRedBg: 'indexRedBg.png',
    indexMain: 'indexMain.png',
    indexPrizeInfo: 'indexPrizeInfo.png',
    indexRedHeart: 'indexRedHeart.png',
    indexGrayHeart: 'indexGrayHeart.png',
    indexAddRedButton: 'indexAddRedButton.png',
    indexInfoBgSex1: 'indexInfoBgSex1.png',
    indexInfoBgSex2: 'indexInfoBgSex2.png',
    indexInfoBgSex3: 'indexInfoBgSex3.png',
    list1Normal: 'list1Normal.png',
    list1Active: 'list1Active.png',
    list2Normal: 'list2Normal.png',
    list2Active: 'list2Active.png',
    list3Normal: 'list3Normal.png',
    list3Active: 'list3Active.png',
    listItemBg1: 'listItemBg1.png',
    list2ItemBg: 'list2ItemBg.png',
    redHeart: 'redHeart.png',
    addRedHeart: 'addRedHeart.png',
    list3CardBg: 'list3CardBg.png',
    list3ItemBg: 'list3ItemBg.png',
    list3ItemBgActive: 'list3ItemBgActive.png',
    list3MIcon: 'list3MIcon.png',
    list3FIcon: 'list3FIcon.png',
    list3PIcon: 'list3PIcon.png',
    list3GIcon: 'list3GIcon.png',
    list3MIconActive: 'list3MIconActive.png',
    list3FIconActive: 'list3FIconActive.png',
    list3PIconActive: 'list3PIconActive.png',
    list3GIconActive: 'list3GIconActive.png',
    cardMActive: 'cardMActive.png',
    cardEActive: 'cardEActive.png',
    cardIActive: 'cardIActive.png',
    cardZActive: 'cardZActive.png',
    cardUActive: 'cardUActive.png',
    cardBack: 'cardBack.png',
    audio: 'audio.png',
    audioMp3: 'ghost.mp3',
    back: 'back.png',
    rod: 'rod.png',
    labelYellow: 'labelYellow.png',
    step1Logo: 'step1Logo.png',
    step1Readme: 'step1Readme.png',
    step1CodeBottom: 'step1CodeBottom.png',
    step1Button: 'step1Button.png',
    step1Text: 'step1Text.png',
    step1Code: 'step1Code.png',
    step2Logo: 'step2Logo.png',
    step2Readme: 'step2Readme.png',
    step2Sex1: 'step2Sex1.png',
    step2Sex2: 'step2Sex2.png',
    step2Sex3: 'step2Sex3.png',
    step2Sex1Active: 'step2Sex1Active.png',
    step2Sex2Active: 'step2Sex2Active.png',
    step2Sex3Active: 'step2Sex3Active.png',
    step3Readme: 'step3Readme.png',
    step3Button: 'step3Button.png',
    step3ButtonDisabled: 'step3ButtonDisabled.png',
    step3Circle1: 'step3Circle1.png',
    step3Circle2: 'step3Circle2.png',
    step3Circle3: 'step3Circle3.png',
    step3Circle4: 'step3Circle4.png',
    step3Circle5: 'step3Circle5.png',
    step3Circle6: 'step3Circle6.png',
    step3Circle7: 'step3Circle7.png',
    step3Circle8: 'step3Circle8.png',
    step3Circle9: 'step3Circle9.png',
    step3Circle10: 'step3Circle10.png',
    step3Logo: 'step3Logo.png',
    step3CircleBg: 'step3CircleBg.png',
    step3CircleBg1: 'step3CircleBg1.png',
    step3CircleBg2: 'step3CircleBg2.png',
    step3CircleBg3: 'step3CircleBg3.png',
    help: 'help.png',
    circle: 'circle.png'
};

var g_res = [];

for(var i in res){
    g_res.push(res[i]);
}
